# Generated by Django 3.2.20 on 2023-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='NIN',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='nationality',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
