# Generated by Django 3.2.20 on 2023-07-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_leadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('waiting', 'Waiting'), ('future', 'Future'), ('prospect', 'Prospect'), ('meeting', 'Meeting')], default='new', max_length=10),
        ),
    ]
